### ISSUE TITLE
Read from a std::io `Read` + `Seek` and output to a `Write`

### ISSUE THREAD

**Issue by sharksforarms** [sharksforarms/deku#105]
Reader functions can take in a `Read` + `Seek` trait impl, write can write to a `Write`

https://github.com/sharksforarms/deku/issues/100

Feature gated under "std" feature as these are std traits.

For nostd, maybe need to wait for: https://github.com/rust-lang/rust/issues/48331

References:
https://doc.rust-lang.org/std/io/trait.Read.html
https://doc.rust-lang.org/std/io/trait.Write.html
https://doc.rust-lang.org/std/io/trait.Seek.html

**Comment by CJKay** [comment]
If anybody's looking for a way to work around this in the meantime, I hacked this up this nightmare:

```rust
fn read_offset<'a, C, T, O>(
    rest: &'a BitSlice<Msb0, u8>,
    input: &'a BitSlice<Msb0, u8>,
    ctx: C,
    offset: O,
) -> Result<(&'a BitSlice<Msb0, u8>, T), DekuError>
where
    C: Copy,
    T: DekuRead<'a, C>,
    O: Into<usize>,
{
    let offset = offset.into();
    let subslice = input.get(offset..).ok_or_else(|| {
        let need = NeedSize::new(rest.len() - offset);

        DekuError::Incomplete(need)
    })?;

    T::read(subslice, ctx)
}

fn read_offset_count<'a, C, T, U, O, N>(
    rest: &'a BitSlice<Msb0, u8>,
    input: &'a BitSlice<Msb0, u8>,
    ctx: C,
    offset: O,
    count: N,
) -> Result<(&'a BitSlice<Msb0, u8>, T), DekuError>
where
    C: Copy,
    T: DekuRead<'a, (Limit<U, fn(&U) -> bool>, C)>,
    U: Copy + DekuRead<'a, C>,
    O: Into<usize>,
    N: Into<usize>,
{
    read_offset(rest, input, (Limit::new_count(count.into()), ctx), offset)
}
```

Example usage:

```
    /// File name hashes.
    #[deku(reader = "read_offset_count(deku::rest, deku::input_bits, endian, ((*file_name_hashes_offset as usize) + 8) * 8, *file_count as usize)")]
    file_name_hashes: Vec<u64>,
```

**Comment by TheWillard** [comment]
I'm curious on how this could be implemented, since this feature would really help in some of my projects. 
If I'm not mistaken, `bitvec` is just a wrapper around a `Vec`, my guess is that we would need to replace it with something like https://github.com/tuffy/bitstream-io or with a trait that is implemented for `bitvec` and `bitstream-io`.
Or maybe I'm missing a simpler solution?

**Comment by XVilka** [comment]
Having this out of the box would really make use of deku easier.

**Comment by wcampbell0x2a** [comment]
Closing, this is now in released deku.
