### ISSUE TITLE
Support magic values prefixing types

### ISSUE THREAD

**Issue by samuelsleight** [sharksforarms/deku#109]
It would be nice to support an attributes similar to `binread`'s `magic` attribute, for specifying a type must start with a given byte sequence, like so:

```rust
#[derive(Debug, DekuRead)]
#[deku(magic = b"ID3")]
pub struct Id3v2 {
   ...
}
```

This is something I have hacked in on a branch ([here](https://github.com/samuelsleight/deku/commit/507ecfccc66b1e10fa53ed7daf168fdda23498f8)), however I figured it would be sensible to open a discussion about it and actually do it properly (and support writing in addition to reading).

**Comment by wcampbell0x2a** [comment]
Somewhat related: https://github.com/sharksforarms/deku/issues/71

**Comment by samuelsleight** [comment]
Ah, I'd misssed that that issue was covering magic values also. 
Potentially the best way of implementing this feature (or at least the reading half of it) is using a hidden `assert_eq` under-the-hood

**Comment by sharksforarms** [comment]
Great idea! Are you interested in submitting a PR with your branch? If not, I can take a look at your branch this week

**Comment by samuelsleight** [comment]
My branch as-is is just something I hacked in to get something working when porting my code from binread, and I'm not necessarily sold on it being the _best_ way of doing things. If you think a PR is a better place to work out what _is_ the best way then I'm happy to open one now, though?

**Comment by sharksforarms** [comment]
No problem! I was mainly trying to figure out intention ;) I appreciate all the maintenance/contribution help I can get! If you wanted to open a PR, I can guide you through the code/adding tests/adding a write impl/docs

**Comment by samuelsleight** [comment]
In that case, I may as well open one then, why not
