### ISSUE TITLE
Read a container until a given condition is met

### ISSUE THREAD

**Issue by samuelsleight** [sharksforarms/deku#110]
There are a couple of use-cases for this: FLAC metadata is read until a given flag in the metadata header is set marking it as the last one, and also for reading null-terminated strings. In both these cases I have manually used a `reader` attribute to read in a loop until said condition holds, however it might be nice to support an `until` attribute on vectors that takes a predicate to call on each item as it is read, for example:

```rust
#[derive(DekuRead)]
struct NullTerminatedString {
    #[deku(until = "|byte| byte == 0")]
    vec: Vec<u8>,
}
```

**Comment by sharksforarms** [comment]
Agreed, this would be useful and is both read/write compatible.

**Comment by samuelsleight** [comment]
So, I've been thinking about this one and I'm leaning towards implementing this by converting the current `Count` context type into an `enum` of either `Count` or `Until` - this feels like a nice clean way of enforcing them being mutually exclusive (which I think they should be) and also doesn't require any new `impl` blocks, we can just modify the current blocks that take `Count`. It's also then nicely extensible with any future ways of reading a `Vec`. It would, however be a breaking change for anybody directly using `Count`, which may or may not be a good idea to introduce.
Do we think this is a good idea?

**Comment by sharksforarms** [comment]
Possibly related: https://github.com/sharksforarms/deku/issues/76

**Comment by sharksforarms** [comment]
> So, I've been thinking about this one and I'm leaning towards implementing this by converting the current `Count` context type into an `enum` of either `Count` or `Until` - this feels like a nice clean way of enforcing them being mutually exclusive (which I think they should be) and also doesn't require any new `impl` blocks, we can just modify the current blocks that take `Count`. It's also then nicely extensible with any future ways of reading a `Vec`. It would, however be a breaking change for anybody directly using `Count`, which may or may not be a good idea to introduce.

Breaking changes are OK with me. This library is still changing and is not committed to stability (1.0) just yet.

> Do we think this is a good idea?

Yes! I think that's a good way of handling mutual exclusivity between different "contexts"
