### ISSUE TITLE
Expose the read byte offset as an available variable

### ISSUE THREAD

**Issue by samuelsleight** [sharksforarms/deku#111]
(Apologies for the train of issues, this is the last one)

I have found it desirable to know how many bytes have been read. As an example, I am currently reading an id3v2 attached picture field like so:

```rust
#[derive(DekuRead)]
#[deku(ctx = "size: u32")]
pub struct Picture {
    encoding: u8,

    #[deku(
        ctx = "BufferKind::NullTerminated, 0",
        map = "EncodedStringBuffer::map"
    )]
    mime_type: String,

    picture_type: u8,

    #[deku(
        ctx = "BufferKind::NullTerminated, *encoding",
        map = "EncodedStringBuffer::map"
    )]
    description: String,

    #[deku(count = "size - (input.offset_from(rest) as u32 / 8)")]
    picture: Vec<u8>,
}
```

where `mime_type` and `description` are null-terminated strings and can therefore be any length, and the `picture` field is just "the rest of the binary data to fill the given field size". I am currently using `input.offset_from(rest)` to calculate this read size, however I do not know if this is actually _intended_ behaviour. Whether it is or not, I think I might be nice to expose this value as an available variable, so that this calculation can simply be something along the lines of `#[deku(count = "size - bytes_read")]`

**Comment by sharksforarms** [comment]
Don't stop the issues! These are great ideas. I'm glad you were able to find a work-around.

This should include better documentation surrounding "internal" but available variables. Possibly finding a better way to expose/express this use case

**Comment by samuelsleight** [comment]
Out of curiosity, is there an list somewhere of the other "internal" variables? It would be a good start to look at that if this is going to include better documentation for them all (which I agree it should)

**Comment by sharksforarms** [comment]
> Out of curiosity, is there an list somewhere of the other "internal" variables?

What I do instead of tracing back proc-macro code is I directly look at the result after it's generated: `cargo expand --example example > examples/out.rs` and take a look at `from_bytes` inside of `out.rs`

What's available:
- `input` tuple
- Previous parsed fields
- `rest`
- (private vars via `__deku_`)

```rust
impl DekuContainerRead for DekuTest {
    fn from_bytes(input: (&[u8], usize)) -> Result<((&[u8], usize), Self), DekuError> {
        use core::convert::TryFrom;
        let input_bits = input.0.view_bits::<Msb0>();
        let mut rest = input.0.view_bits::<Msb0>();
        rest = &rest[input.1..];
        let __deku_field_a = {
            let (new_rest, value) = DekuRead::read(rest, (deku::ctx::BitSize(9usize)))?;
            let value: u8 = Result::<_, DekuError>::Ok(value)?;
            rest = new_rest;
            value
        };
        let field_a = &__deku_field_a;
        let __deku_field_b = {
            let (new_rest, value) = DekuRead::read(rest, (deku::ctx::BitSize(9usize)))?;
            let value: u8 = Result::<_, DekuError>::Ok(value)?;
            rest = new_rest;
            value
        };
        let field_b = &__deku_field_b;
        let value = Self {
            field_a: __deku_field_a,
            field_b: __deku_field_b,
        };
        let pad = 8 * ((rest.len() + 7) / 8) - rest.len();
        let read_idx = input_bits.len() - (rest.len() + pad);
        Ok(((input_bits[read_idx..].as_slice(), pad), value))
    }
}
```

**Comment by samuelsleight** [comment]
I forgot cargo expand existed, that's a super helpful one!

We're happy then that `input` and `rest` are intended to be accessed? My main worry with what I'd done was that it seemed to be relying on implementation detail - documenting these (and any additional variables added to make this nicer) will help with that though, if it is indeed intended.

**Comment by sharksforarms** [comment]
> We're happy then that `input` and `rest` are intended to be accessed? My main worry with what I'd done was that it seemed to be relying on implementation detail - documenting these (and any additional variables added to make this nicer) will help with that though, if it is indeed intended.

Yes they're intended (for now, [see example here](https://docs.rs/deku/0.8.0/deku/attributes/index.html#readerwriter)) until a better solution can be thought of. I'm not a huge fan of this as it makes it hard to discover (unless you're well versed in the documentation!) Better documentation of these exposed variables would be beneficial for now.

**Comment by sharksforarms** [comment]
@samuelsleight I'm working on this now, having troubles coming up with a good example to put in the documentation. Would you be able to provide a short example?

**Comment by samuelsleight** [comment]
@sharksforarms A common pattern in a lot of the fields in ID3v2 metadata is that we read the size of the entire block of metadata, then some bytes or flags or whatever as part of that metadata, and then a string or binary data at the end which is just "the rest of the size" - a super minimal example of this sort of thing could be:
```rust
#[derive(DekuRead)]
#[deku(ctx = "size: u32")]
pub struct EncodedString {
    encoding: u8,

    #[deku(count = "size - this_offset")]
    data: Vec<u8>
}
```
That example _could_ trivially use `size - 1` instead, but I think it's the most minimal example that shows it off. 

A slightly more complex example to show a more reasonable usage could be a stripped down version of what I initially put in the issue - reading the picture field reads a null terminated string describing the picture, and then the rest of the size is the binary picture data:
```rust
#[derive(DekuRead)]
#[deku(ctx = "size: u32")]
pub struct Picture {
    #[deku(until = |v: u8| v == 0u8)]
    description: Vec<u8>

    #[deku(count = "size - this_offset")]
    data: Vec<u8>
}
```

**Comment by sharksforarms** [comment]
Thanks! @samuelsleight 

How does this look? `byte_offset` and `bit_offset` will be available (only if referenced)

```rust
#[derive(DekuRead)]
#[deku(ctx = "size: u32")]
pub struct EncodedString {
    encoding: u8,

    #[deku(count = "size as usize - byte_offset")]
    data: Vec<u8>
}
```

The variables will be documented, I'm still debating on namespacing them somehow... `deku_byte_offset`? `deku(rest)`? none at all?

**Comment by samuelsleight** [comment]
@sharksforarms That looks good to me!

re namespacing - it's probably a sensible idea to do so? is it possible to get regular path syntax for them, i.e. `deku::byte_offset`? That feels the most intuitive to me I think?

**Comment by sharksforarms** [comment]
@samuelsleight yeah that looks nice! It will basically be a string find/replace for everything prefixed with `deku::`.

At the same time, I think `rest`, `input` and `output` should also be namespaced `deku::rest`

**Comment by samuelsleight** [comment]
Yeah, I'm for that. It might be a breaking change but I think it's much nicer
