### ISSUE TITLE
Add support for unused/padding bits

### ISSUE THREAD

**Issue by elast0ny** [sharksforarms/deku#12]
It would be nice if there was a way to skip over bits or bytes without creating dummy fields in order to save on space e.g : 
```Rust
pub struct SomeStruct {
    field_01: u8,

    // This field is useless but is needed for proper read/write
    unused01: u8,

    field_02: u8,

    // This field is useless but is needed for proper read/write
    unused02: u8,
}
```

maybe some `skip_[bytes|bits]` that could be added before and after fields in structs :
```Rust
#[deku(skip_bytes="1")]
```

**Comment by sharksforarms** [comment]
Yes, I think a "skip" attribute would be useful, the `bits/bytes` sizes can be re-used. I think it would still need to be added to a field though..

I'm also thinking the naming `skip` could be used for something else, for example:

```rust
struct SomeStruct {
    #[deku(bits = "6")]
    field_a: u8,

    #[deku(skip, map = "to_string(field_a)" )]
    field_a_as_string: String,

    field_b: u8,
}
```

If a user really wanted to "skip", the user could specify a custom reader/writer, would that be sufficient? These types of utility functions could be provided by deku, i.e.
```rust
struct SomeStruct {
    #[deku(bits = "6")]
    field_a: u8,

    #[deku(reader = "deku::utils::skip_x_bits(2)", writer = "")]
    _unused: u8,

    field_b: u8,
}
```

**Comment by sharksforarms** [comment]
Alternatively, `ignore` might be a good name

```rust
struct SomeStruct {
    #[deku(bits = "6")]
    field_a: u8,

    #[deku(ignore, bits = "2")]
    _unused: u8,

    field_b: u8,
}
```

**Comment by wcampbell0x2a** [comment]
Would this be possible?
```
struct SomeStruct {
    #[deku(bits = "6")]
    field_a: u8,
    #[deku(ignore, bits = "2")]
    field_b: u8,
}
```

Where 6 bits are read, then 2 are ignored, then 8 are read for u8. Without a dummy struct field.

**Comment by sharksforarms** [comment]
> Would this be possible?
> 
> ```
> struct SomeStruct {
>     #[deku(bits = "6")]
>     field_a: u8,
>     #[deku(ignore, bits = "2")]
>     field_b: u8,
> }
> ```
> 
> Where 6 bits are read, then 2 are ignored, then 8 are read for u8. Without a dummy struct field.

@wcampbell0x2a, it may be possible yes. It is required to have a field though. Just to expand on the example, something like this could be interesting, not sure if they're combined or not... needs experimentation

```rust
struct SomeStruct {
    #[deku(bits = "6")]
    field_a: u8,
    #[deku(ignore, bits = "2")]
    #[deku(bits = "6")]
    field_b: u8,
}
```
