### ISSUE TITLE
Getting rid of additional member when using `count`

### ISSUE THREAD

**Issue by oleid** [sharksforarms/deku#120]
This is a really good l looking library!  But reading the documentation, I was wondering, why one would keep the redundant vector length member  around, e.g in the following struct:

```rust
#[derive(Debug, PartialEq, DekuRead, DekuWrite)]
struct DekuTest {
    num_items: u8,
    #[deku(count = "num_items", endian = "big")]
    items: Vec<u16>,
}
```
Aside from being redundant, having to call `update()` after appending to `items()` strikes me as a subtle source of errors I'd very much like to avoid. 

If I'd to parse this kind data with `nom`, `num_items` wouldn't be a member, but only a temporary when reading. And it would automatically be generated from the length of the vector when writing. 

Would this be currently possible? And if not, how would you feel about such a feature?

**Comment by sharksforarms** [comment]
I agree it's a subtlety that users need to be careful about and could be a source of error.

Initially, this is how I designed it, `num_items` would get updated upon writing.

However, there's problems with this approach:
- The struct now implicitly requires to be `mut` and functions need to take a `&mut` even if no Vec is present
- User now no longer has full control over the length (this is useful when fuzzing)

This is why I made a `update` attribute.

I'm open to ideas!

**Comment by samuelsleight** [comment]
This feels like it could be nicely handled in a similar way to the `type` attribute on `enums`? 

i.e., given the following:
```rust
#[deku(count = "u8")]
items: Vec<u16>
```

we'd read a `u8` for the size and then read that many items into the vec, and for writing would write the vec size as a `u8` and then write out the items - this would be exactly equivalent to the example struct in the issue, but without the explicit `num_items` member.

**Comment by sharksforarms** [comment]
@oleid, @samuelsleight see https://github.com/sharksforarms/deku/pull/136 :)

**Comment by constfold** [comment]
According to https://github.com/sharksforarms/deku/issues/120#issuecomment-717098394, now seems like here are two different types of `Vec`: one only stores items and another stores the length and items.
```rust
v1: Vec<T> // <-- only stores items, so length is required in read and update is required on write
v2: LenVec<T> // <-- stores both items and length, so will not need extra length on read and write
```
Maybe we should add a new attribute to offer the ability to choose which type of vec is wanted? e.g.:
```rust
#[deku(store_len)]
v: Vec<T>
```
But comparing to the normal `Vec`, the limitation of `LenVec` is that it's hard to say the position the length stored(in the top of struct? or at the bottom? or followed by a specific field?)
Anyway, no matter what the the right design is, I think we all agree that the current `update` resolution is imperfect and should be  improved.

**Comment by sharksforarms** [comment]
I feel like `LenVec<T>` could be created by a user with a custom reader/writer. Maybe best to provide an example in the repo or docs. This way the user specifies exactly what they want for their use case.

**Comment by sharksforarms** [comment]
Closing for now.
