### ISSUE TITLE
Versioning 

### ISSUE THREAD

**Issue by oleid** [sharksforarms/deku#121]
What would be the idiomatic way to support versioning resp. different variants?

I have, for example, the following  data:

```
Short_len: u8
If Short_len == 255: Long_Len: u16
```
Of curse, in the parsed struct, I would only want to save an u16. Similar, if the struct had a version field, I would not want that to be a member of the struct. It should only be used as a temporary value to decide which parser variant should be used.  What would be an idiomatic way to do that?

**Comment by sharksforarms** [comment]
There's different ways depending on how you'd like to approach it and how your format is laid out, here's two examples using a struct or an enum.

Really depends on your data format. Remember the symmetrical nature of the library, when writing out the struct, it writes the same format that it read. If this isn't the case let me know and I can provide a more advanced example using custom reader and writer attributes. If you can provide the raw bytes and an example test case (like below) this would help me help you

struct
```rust
use deku::prelude::*;

#[derive(Debug, PartialEq, DekuRead, DekuWrite)]
struct VersionTest {
    short_len: u8,
    #[deku(cond = "*short_len == 255")] // condition to parse long_len
    long_len: Option<u16>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::convert::{TryFrom, TryInto};

    #[test]
    fn test_version() {
        let data: Vec<u8> = vec![
            255, // short_len = 255
            0xCD, 0xAB // long_len = 0xABCD
        ];

        let ret_read = VersionTest::try_from(data.as_ref()).unwrap();

        assert_eq!(
            VersionTest {
                short_len: 255,
                long_len: Some(0xABCD), // parsed long_len because short_len == 255
            },
            ret_read
        );

        let ret_write: Vec<u8> = ret_read.try_into().unwrap();
        assert_eq!(data, ret_write);
    }
}
```

enum
```rust
use deku::prelude::*;

#[derive(Debug, PartialEq, DekuRead, DekuWrite)]
struct VersionTest {
    short_len: u8,
    #[deku(cond = "*short_len == 255")] // condition to parse long_len
    long_len: Option<u16>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::convert::{TryFrom, TryInto};

    #[test]
    fn test_version() {
        let data: Vec<u8> = vec![
            255, // short_len = 255
            0xCD, 0xAB // long_len = 0xABCD
        ];

        let ret_read = VersionTest::try_from(data.as_ref()).unwrap();

        assert_eq!(
            VersionTest {
                short_len: 255,
                long_len: Some(0xABCD), // parsed long_len because short_len == 255
            },
            ret_read
        );

        let ret_write: Vec<u8> = ret_read.try_into().unwrap();
        assert_eq!(data, ret_write);
    }
}
```

**Comment by oleid** [comment]
Thanks for the examples. So in essence, I would create temporary (parsing/writing-only) structs or enums like VersionTest, which would then be converted into a representation I would like to use in the rest of the program?

**Comment by sharksforarms** [comment]
If you're only doing reading and don't care about writing it back out (like nom) you could do something like this:

```rust
use deku::prelude::*;

#[derive(Debug, PartialEq, DekuRead)]
struct VersionTest {
    #[deku(reader = "VersionTest::read_length(rest)")]
    length: u16,
}

impl VersionTest {
    fn read_length(rest: &BitSlice<Msb0, u8>) -> Result<(&BitSlice<Msb0, u8>, u16), DekuError> {
        let (rest, length) = u8::read(rest, ())?;

        if length == 255 {
            u16::read(rest, ())
        } else {
            Ok((rest, u16::from(length)))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::convert::TryFrom;

    #[test]
    fn test_version_short() {
        let data: Vec<u8> = vec![254];

        let ret_read = VersionTest::try_from(data.as_ref()).unwrap();

        assert_eq!(VersionTest { length: 254 }, ret_read);
    }

    #[test]
    fn test_version_long() {
        let data: Vec<u8> = vec![255, 0xCD, 0xAB];

        let ret_read = VersionTest::try_from(data.as_ref()).unwrap();

        assert_eq!(VersionTest { length: 0xABCD }, ret_read);
    }
}
```

**Comment by oleid** [comment]
I think writing back would be nice as well :)
This format is really grown. No sane person would do it like this. 
I guess separate readers and writers would make sense.

But in general, I'm usually not interested in having a version field in my structs, it would only be a temporary value used to decide how to parse. Writing would always be in the latest version. So I guess what I wondered about in #120 is actually related.

**Comment by oleid** [comment]
The more I think about it, the more I like the enum approach. Not for the insane length example, but in general. The enum plus an implementation of From<TheEnum> for the final type, which handles missing information. That may be a little verbose, but it makes things more obvious.
