### ISSUE TITLE
Implement Read+Write HashMap/HashSet

### ISSUE THREAD

**Issue by sharksforarms** [sharksforarms/deku#129]
Similar implementation to Vec, where `length` is the number of key/val pairs

**Comment by samuelsleight** [comment]
Oooh, this feels like it could be nicely done by making some `DekuContainer` trait with an associated type for the container item type and a `push` method, and then the existing `impl Deku{Read,Write} for Vec` becomes a generic implementation for types implementing that trait.

`Vec` and `HashSet` cal implement that trait with their value type as the item type, and `HashMap` could then implement it with a `(Key, Value)` pair as the type (assuming we have existing `Deku{Read,Write}` implementations for tuples?)

**Comment by abungay** [comment]
> 
> 
> Oooh, this feels like it could be nicely done by making some `DekuContainer` trait with an associated type for the container item type and a `push` method, and then the existing `impl Deku{Read,Write} for Vec` becomes a generic implementation for types implementing that trait.
> 
> `Vec` and `HashSet` cal implement that trait with their value type as the item type, and `HashMap` could then implement it with a `(Key, Value)` pair as the type (assuming we have existing `Deku{Read,Write}` implementations for tuples?)

Some great ideas! I have opened a PR to implement HashMap and HashSet for now without these new DekuContainer trait changes but we could refactor these to have more reuse between the implementations of HashMap and HashSet and other containers in the future :)
