### ISSUE TITLE
Compile time bit_size checking

### ISSUE THREAD

**Issue by elast0ny** [sharksforarms/deku#13]
https://github.com/sharksforarms/deku/blob/26eccca325c37b847b3c1ea7032045e26f8ca752/deku-derive/src/macros/deku_read.rs#L79

This seems like it could be fixed by using `const` functions. std::mem::size_of() is `const` which can all be evaluated at compile time. e.g. :
```Rust
    const fn bit_size() -> usize {
        std::mem::size_of::<$typ>() * 8
    }
```

**Comment by sharksforarms** [comment]
I wonder if the assert could be done at compile time? For example, this would fail to compile

```rust
struct DekuTest {
    #[deku(bits = "9")]
    field_a: u8,
}
```

**Comment by elast0ny** [comment]
This should be possible with :
https://docs.rs/static_assertions/1.1.0/static_assertions/macro.const_assert.html

**Comment by elast0ny** [comment]
oh crap : https://github.com/rust-lang/rust/issues/57563

**Comment by sharksforarms** [comment]
No longer required: https://github.com/sharksforarms/deku/pull/19
