### ISSUE TITLE
Skip over or offset attribute

### ISSUE THREAD

**Issue by passcod** [sharksforarms/deku#142]
I have a situation where a field is a lookup table for another later field, but when parsing the entire structure at once, it's not useful to make use of the lookup. I still need to declare it to deku to parse properly, though:

```rust
const LOOKUP_SIZE: usize = 12;

#[derive(DekuRead)]
struct SometimesLazy {
	#[deku(bytes = 4)]
	count: usize,
	#[deku(count = "count * LOOKUP_SIZE")]
	_lookup: Vec<u8>,
	#[deku(count = "count")]
	actual_data: Vec<Item>,
}
```

Currently I map it to nothing:

```rust
#[deku(count = "count * LOOKUP_SIZE", map = "|table: Vec<u8>| -> Result<(), DekuError> { Ok(()) }")]
_lookup: (),
```

However, that's still parsing out the field. I'd rather be able to tell deku to skip over N bytes:

```rust
#[deku(skip_bytes = "count * LOOKUP_SIZE")]
_lookup: (),
```

Or as an offset on the next field:

```rust
#[deku(bytes = 4)]
count: usize,
#[deku(count = "count", offset_bytes = "count * LOOKUP_SIZE")]
actual_data: Vec<Item>,
```

**Comment by sharksforarms** [comment]
Are these bytes you're simply not interested in and which to discard? Possibly duplicating: https://github.com/sharksforarms/deku/issues/12

A potential alternative is to use `#[deku(temp)]` pending release. This would still go down the code path of reading, but wouldn't be stored in your final struct: https://github.com/sharksforarms/deku/pull/136

**Comment by passcod** [comment]
Ah yeah, #12 is it
