### ISSUE TITLE
Enums with non-integer discriminant types

### ISSUE THREAD

**Issue by passcod** [sharksforarms/deku#143]
For example, `[u8; 3]`.

I worked around this by using a detached id passed down as context and cast to some integer, but it would be nice to have arbitrary type support there, or at least bytes sequences.

**Comment by sharksforarms** [comment]
So something like the following right?

```rust
#[derive(Debug, PartialEq, DekuRead, DekuWrite)]
#[deku(type = "[u8; 3]")]
enum DekuTest {
    #[deku("[1,1,1]")]
    VarA,
}
```

**Comment by passcod** [comment]
Yes, or even with `b"ABC"` if possible

**Comment by passcod** [comment]
To give context, this came up with the gearman protocol which has a request/response sequence at the top of every packet as a nul byte followed by `b"REQ"` or `b"RES"`.

Workaround in that case was to include the null byte and treat the entire thing as a u32, but that hinders readability and prevents some parsing in that case (the nul byte is really its own discriminant, indicating that the packet is of one subprotocol — it works out here because I'm not implementing the other subprotocol).

**Comment by sharksforarms** [comment]
Should be do-able there's a couple spots which need to be changed.
