### ISSUE TITLE
Refactor DekuError

### ISSUE THREAD

**Issue by anti-social** [sharksforarms/deku#167]
It would be nice to be able to distinguish such an error from others. Especially useful when implementing network protocol parsers.
At the moment it is only possible to check `DekuError::Parse(msg) if msg.starts_with("not enough data")` that doesn't seem like a reliable solution.

I suggest to add an enum variant for this case:
```
Incomplete(NeedSize)
```
or
```
NotEnoughData(NeedSize)
```

Also `DekuError` enum could be non-exhaustive to not break backward compatibility.

I could make a PR if you agree with the issue.

**Comment by sharksforarms** [comment]
I agree the error handling story is not complete. The error enum should be non-exhaustive and should properly give the user a way to handle errors. Stringly typed errors are not ideal. I intended to look into the latest flavor of error handling libraries, I'm not opposed to using `thiserror` for example to make the experience nicer.

A PR would be awesome!

**Comment by sharksforarms** [comment]
It has come to my attention that `thiserror` is not yet no_std: https://github.com/dtolnay/thiserror/pull/64

**Comment by sharksforarms** [comment]
@anti-social In master there's now a `DekuError::Incomplete` where you can get the number of bits (or minimum number of bytes) required to try parsing again.

I'll leave this issue open as I think more improvements could be done to the error handling. Still not a fan of the String errors

**Comment by sharksforarms** [comment]
Closing for now, we can modify errors as needed in the future.
