### ISSUE TITLE
Add debug attribute

### ISSUE THREAD

**Issue by wcampbell0x2a** [sharksforarms/deku#168]
It would be helpful to have a `debug` attribute for easier debugging the decode/encode process. It would do the following:
- Display the bits before reading in T (`.view_bits()`)
- Display result of T
- Display the bits after reading in T (`.view_bits()`)

I *think* this could be implemented for both `field` and `top-level` attributes.

**Comment by sharksforarms** [comment]
Yes, there needs to be a better way to debug parsers. I don't mind the idea, I think a mix of logging throughout the crate and a debug attribute like you mentioned could be used. This could be feature gated, to avoid unnecessary checks.

**Comment by wcampbell0x2a** [comment]
I've never used any logging crates,  do you have one in mind?

**Comment by sharksforarms** [comment]
https://github.com/rust-lang/log#in-libraries

**Comment by wcampbell0x2a** [comment]
Our usage wouldn't technically be `in-libraries`, since it's mostly emitted code.

**Comment by wcampbell0x2a** [comment]
Closing, the feature `logging` works for this
