### ISSUE TITLE
Access to an enum id inside of enum's variant

### ISSUE THREAD

**Issue by anti-social** [sharksforarms/deku#169]
Sorry for a question in issues but I cannot connect to the discord channel: 
> This invite may be expired, or you might not have permission to join.

I want an to implement an enum one of the variant of which should access enum's `id`: 
```rust
#[derive(DekuRead, Debug, PartialEq)]
#[deku(endian = "big", type = "u8")]
enum Security {
    #[deku(id = "0x0")]
    FailedReason {
        _len: u32,
        #[deku(count = "_len")]
        reason: Vec<u8>,
    },
    #[deku(id_pat = "_")]
    Types(
        #[deku(count = "id")] // <== not found in this scope
        Vec<u8>,
    ),
}
```

I can only do that by adding some wrapper struct:
```rust
#[derive(DekuRead, Debug, PartialEq)]
#[deku(endian = "big")]
struct Security {
    id: u8,
    #[deku(ctx = "*id")]
    inner: SecurityInner,
}

#[derive(DekuRead, Debug, PartialEq)]
#[deku(endian = "big", ctx = "endian: deku::ctx::Endian, id: u8", id = "id")]
enum SecurityInner {
    #[deku(id = "0x0")]
    FailedReason {
        _len: u32,
        #[deku(count = "_len")]
        reason: Vec<u8>,
    },
    #[deku(id_pat = "_")]
    Types(
        #[deku(count = "id")]
        Vec<u8>
    ),
}
```

But possibly I missed something.

**Comment by wcampbell0x2a** [comment]
Internally, this is known as `variant_id` and is not namespaced.

Thus, the following works:
```
#[derive(DekuRead, Debug, PartialEq)]
#[deku(endian = "big", type = "u8")]
enum Security {
    #[deku(id = "0x0")]
    FailedReason {
        _len: u32,
        #[deku(count = "_len")]
        reason: Vec<u8>,
    },
    #[deku(id_pat = "_")]
    Types(
        #[deku(count = "variant_id")]
        Vec<u8>,
    ),
}

mod tests {
    use super::*;

    #[test]
    fn test() {
        let security = Security::from_bytes((&[0x00, 0x00, 0x00, 0x00, 0x01, 0x02], 0));
        println!("{:#?}", security);
        let security = Security::from_bytes((&[0x02, 0x00, 0x00, 0x00, 0x01, 0x02], 0));
        println!("{:#?}", security);
    }
}
```

**Comment by sharksforarms** [comment]
Good catch @wcampbell0x2a , this should be namespaced.

**Comment by anti-social** [comment]
Thanks for your help.

In second case I would expect:
```rust
Security::Types(vec!(0u8, 0u8))
```
but get:
```rust
Security::Types(vec!(2u8, 0u8))
```

Somehow size of the vector becomes its first element.

**Comment by sharksforarms** [comment]
> Thanks for your help.
> 
> In the second case I would expect:
> 
> ```rust
> Security::Types(vec!(0u8, 0u8))
> ```
> 
> but get:
> 
> ```rust
> Security::Types(vec!(2u8, 0u8))
> ```
> 
> Somehow size of the vector becomes its first element. Seems like it is not consumed from the input.

This is expected,

"The enum variant must have space to store the identifier for proper writing."
https://docs.rs/deku/0.10.0/deku/attributes/index.html#id_pat

When `id_pat` is used, the read `id` needs to be stored in the variant to be able to have a proper symmetric write. This is not the case with `id` as the value is static.

You can do something like this:
Note: added `id`
```rust
    #[deku(id_pat = "_")]
    Types {
        id: u8,
        #[deku(count = "id")]
        data: Vec<u8>,
    },
```

**Comment by sharksforarms** [comment]
I changed the discord to gitter instead, updated the README: https://gitter.im/rust-deku/community

**Comment by anti-social** [comment]
Thank you again
