### ISSUE TITLE
Allow the option to partially write a binary

### ISSUE THREAD

**Issue by etra0** [sharksforarms/deku#173]
Hi, first of all, I'm loving Deku so far, it's so easy to parse binaries it's crazy.

I'd like to know how possible is to create a way of updating an already loaded binary (not appending, updating values) when there are unknown offsets.

Let's say I'm reversing a file and I discovered just enough information that I needed and I want to parse those values, allow the user to change them, then I'd like to update only those values in the original file. 

Right now the _I think_ it can't be done since the option `pad_bytes_after` and `pad_bytes_before` adds 0 to the binary output (unless I missed something on the docs).

**Comment by sharksforarms** [comment]
Could you provide an example? Even pseudo-code would suffice.

There is an `update` attribute which can be used to update the value on the struct, but if I understand correctly, you're parsing on part of the file:

`let (rest, header) = Header::from_bytes(input);`

`rest` will contain the un-parsed data (rest of file)

**Comment by etra0** [comment]
Sure, let's say I currently have something like this:
```rs
#[derive(DekuRead, DekuWrite)]
#[deku(magic = b"YZFH")]
pub struct SaveFile {
    #[deku(pad_bytes_before = "0x24")]
    pub time: SaveTime,

    #[deku(pad_bytes_before = "0x40F")]
    pub difficulty: Difficulty,
}
```

but the binary does have information between the time and difficulty values that I don't need to parse but I need to keep for the end result, and they're skipped because of the `pad_bytes_before` (or rather filled with 0s). An option would be to just add the difference as an `unk` field of the size of the skipped bytes, but then if I want to use Serde, that would include a big array in the json.

**Comment by sharksforarms** [comment]
If you need to `DekuWrite`, you need to keep track of the bytes which were read.

```rust
#[derive(DekuRead, DekuWrite)]
#[deku(magic = b"YZFH")]
pub struct SaveFile {
    #[deku(count = "0x24")]
    _data1: Vec<u8>,
    pub time: SaveTime,

    #[deku(count = "0x40")]
    _data2: Vec<u8>
    pub difficulty: Difficulty,
}
```

There is `deku::byte_offset` which you could use in your writer, you're thinking of using this offset to reference the original input upon write? That could be possible too.

https://docs.rs/deku/0.10.0/deku/#internal-variables-and-previously-read-fields

**Comment by etra0** [comment]
Thanks a lot for the response, I _definitely_ missed things of the docs (really sorry!)

**Comment by sharksforarms** [comment]
No worries, the docs could use some improvement for discoverability
