### ISSUE TITLE
Parenthesize attributes in `quote!`

### ISSUE THREAD

**Issue by MrNbaYoh** [sharksforarms/deku#193]
This does not compile:
```rust
#[derive(Debug, DekuRead, DekuWrite, PartialEq)]
struct A {
    #[deku(update = "1+self.data.len()")]
    a: u32,
    #[deku(count = "a")]
    b: Vec<u8>
}
```
while this does:
 ```rust
#[derive(Debug, DekuRead, DekuWrite, PartialEq)]
struct A {
    #[deku(update = "(1+self.data.len())")]
    a: u32,
    #[deku(count = "a")]
    b: Vec<u8>
}
```
because `#field_update` is not parenthesized in https://github.com/sharksforarms/deku/blob/81468e8d27380bf148ae6f098623ed31a2f06395/deku-derive/src/macros/deku_write.rs#L412

**Comment by MrNbaYoh** [comment]
This is also a problem with `pad` attributes:
https://github.com/sharksforarms/deku/blob/81468e8d27380bf148ae6f098623ed31a2f06395/deku-derive/src/macros/mod.rs#L303-L305

**Comment by sharksforarms** [comment]
Fixed, pending release. Thanks for the report!
