### ISSUE TITLE
Emit Enum::BITS

### ISSUE THREAD

**Issue by wcampbell0x2a** [sharksforarms/deku#223]
In [bintex-derive](https://github.com/wcampbell0x2a/bintex/blob/e95193a60db481e7f5b9969b1e0620366a78fe32/bintex-derive/src/lib.rs#L92) I use the `<T>::BITS` constant for types without `#[{deku/bintex}(bits = "num")]` attributes. I would like to do the same when parsing the bit size of an enum.

```
#[deku(type = "u8", bits = "4")]
enum DekuTest {
    #[deku(id = "0b1001")]
    TestA,
}
```

emit:
```
impl DekuEnumExt for DekuTest {
    pub const BITS: usize = 4;
}
```

Just wanted to get your input/approval before I write this. Or any edge cases I can't think of.

**Comment by wcampbell0x2a** [comment]
Actually, an edge cases is the following example, in which we maybe return 16?
```
#[deku(type = "u8", bits = "4")]
enum DekuTest {
    #[deku(id = "0b1001")]
    VariantA( #[deku(bits = "4")] u8, u8),
}

```

**Comment by sharksforarms** [comment]
> Actually, an edge cases is the following example, in which we maybe return 16?
> ```
> #[deku(type = "u8", bits = "4")]
> enum DekuTest {
>     #[deku(id = "0b1001")]
>     VariantA( #[deku(bits = "4")] u8, u8),
> }
> 
> ```

Yeah so in this case there's a Key and a Value... Not sure a BITS makes sense. Could work on enums which only contain values like so?

```rust
enum Test {
    A = 1
}
```
