### ISSUE TITLE
RFE: Support for bstr

### ISSUE THREAD

**Issue by v1gnesh** [sharksforarms/deku#227]
Seeing that we're working with binary data, and UTF-8 validity may not be necessary always, will `deku` work for `bstr` types in place of `String`s defined inside data types?

https://github.com/BurntSushi/bstr

**Comment by sharksforarms** [comment]
Sure! You could use a custom reader/writer or alternatively there's a PR now for an 'as' attribute which could help here too.

**Comment by v1gnesh** [comment]
Okay, another Q - will removing UTF8 validation result in any sort of noticeable performance gain, when parsing gig(s) of data?

**Comment by sharksforarms** [comment]
I'm not sure of the performance implications of bstr vs String, that's a better question for bstr :)

**Comment by v1gnesh** [comment]
Okay, thanks again. 
Guess this means you can close this one.

**Comment by constfold** [comment]
Sry but I didn't get the point. Whats the different between bstr and `[u8]`? Can't you just use `[u8]` if no requirement of UTF-8 validity?

**Comment by v1gnesh** [comment]
I'll be doing some codepage conversion on `&[u8]`, so after that, it'll be a 'string'.
However, I want to avoid the cost (if any) of UTF8 validation, and avoid unsafe code (if it comes to that).
