### ISSUE TITLE
Vec<u8> with remaining bytes

### ISSUE THREAD

**Issue by lukaswozniak** [sharksforarms/deku#228]
Is it possible to have field of type Vec\<u8\>, which will take all remaining bytes?

I can't use `count` attribute because I dont know the exact length upfront.
I tried using `#[deku(until = "|_: &u8| false")]`, but it fails with `Not enough data, need 8 bits (or 1 bytes)`.

Btw thanks for this excellent library :)

**Comment by lukaswozniak** [comment]
Actually I found a way around: `#[deku(count = "deku::rest.len()/8")]`

**Comment by sharksforarms** [comment]
That works, here's the other internal variables you can use:
https://docs.rs/deku/0.12.2/deku/#internal-variables-and-previously-read-fields

Another way could be `deku::input.0.len() - deku::byte_offset`

**Comment by duskmoon314** [comment]
This seems to only work for `struct`. I wonder how to have `Vec<u8>` in `enum`?

Specifically, I want to parse an enum like this:

```rust
#[derive(DekuRead)]
         ^^^^^^^^ the trait `deku::DekuRead<'_>` is not implemented for `Vec<u8>`
enum E {
    #[deku(id = "...")]
    A(Vec<u8>),
    #[deku(id = "...")]
    B(OtherStruct),
}
```
