### ISSUE TITLE
Add a note about the possible performance impact of debug / non optimised Deku implementations

### ISSUE THREAD

**Issue by grantperry** [sharksforarms/deku#232]
I mention this topic, because it took me a few days to find out why one of my structs was taking ~7ms to `T::from_bytes`. I finally realized that I did not encounter this performance issue when compiling --release binaries. I found changing `opt-level >= 2` significantly improved performance of Deku in non-release profiles

If this an issue others have experienced, can I suggest a note in the docs/README.

Thanks for an awesome crate.

**Comment by sharksforarms** [comment]
Thanks for the heads up! This is generally the case in rust and not specifically deku, I'll hold off on this for now unless it's specifically project/crate related
