### ISSUE TITLE
Sign-extending signed integer types?

### ISSUE THREAD

**Issue by korrat** [sharksforarms/deku#236]
Currently, `deku` deserializes signed integers with limited bit width like unsigned integers, as evidenced by the following (passing) test:

```rust
use deku::{bitvec::BitSlice, ctx::Size, DekuRead as _};

#[test]
fn sign_extending() {
    let bits = &BitSlice::from_slice(&[0x1Fu8]).unwrap()[3..];
    let (_rest, num) = i16::read(bits, Size::Bits(5)).unwrap();

    assert_eq!(num, 31);
}
```

I would expect `num` to be `-1` instead, similar to how bit fields in C behave ([Compiler Explorer example](https://godbolt.org/z/c8Mjjf8c8)).

Is this something that could be supported? Perhaps using another context argument?

**Comment by sharksforarms** [comment]
Essentially, we're reading from a byte. Do you have an example on how to get the result you're looking for in rust/bitvec? It may be possible!

https://github.com/sharksforarms/deku/blob/master/src/impls/primitive.rs#L88
