### ISSUE TITLE
How to reference parent field from update attribute on subtype

### ISSUE THREAD

**Issue by ciarant** [sharksforarms/deku#241]
Hi there 👋 . I'm using Deku to try and implement an existing network protocol. The protocol packet has a header and payload ( the example below is similar in structure). The payload is a String `name` field), and the Header contains a `name_len` field to hold the length of the String.

The problem is that I can't figure out how to reference the `name` field in the `update` attribute on the `name_len` field in the Header. Header appears in the Packet before `name` so I don't think I can use `ctx` (I may be incorrect here).

```rust
#[derive(PartialEq, Debug, DekuRead, DekuWrite)]
struct Header {
    #[deku(update = "how do I reference the name field in Packet?")]
    name_len: u8,
}

#[derive(PartialEq, Debug, DekuRead, DekuWrite)]
struct Packet {
    header: Header,
    #[deku(
    count = "header.name_len",
    map = "|field: &[u8]| -> Result<_, DekuError> { Ok(std::str::from_utf8(field).unwrap().to_owned()) }",
    writer = "Packet::write(deku::output, &self.name)"
    )]
    name: String,
}

impl Packet {
    fn write(output: &mut BitVec<Msb0, u8>, value: &str) -> Result<(), DekuError> {
        let bytes = value.as_bytes();
        let _ = output.write(bytes);
        Ok(())
    }
}
```

Given that I don't have the option of modifying the protocol, I guess what I could do is _flatten_ the header and just inline its fields into the `Packet` struct - but I'd rather see if there's a more correct way of achieving my goal.

Any thoughts greatly appreciated. Thank you! 🙇

**Comment by wcampbell0x2a** [comment]
Hey! Sorry I didn't see this issue. This is one way to solve that issue:
```
use deku::bitvec::{BitSlice, BitVec, Msb0};
use deku::prelude::*;

#[derive(PartialEq, Debug, DekuRead, DekuWrite)]
struct Header {
    name_len: usize,
}

impl From<usize> for Header {
    fn from(name_len: usize) -> Self {
        Self { name_len }
    }
}

#[derive(PartialEq, Debug, DekuRead, DekuWrite)]
struct Packet {
    #[deku(update = "self.name.len()")]
    header: Header,
    #[deku(
        reader = "Self::read(deku::rest)",
        writer = "Self::write(deku::output, &self.name)"
    )]
    name: String,
}

impl Packet {
    /// Read and convert to String
    fn read(rest: &BitSlice<Msb0, u8>) -> Result<(&BitSlice<Msb0, u8>, String), DekuError> {
        let (rest, value) = u8::read(rest, ())?;
        Ok((rest, value.to_string()))
    }

    /// Parse from String to u8 and write
    fn write(output: &mut BitVec<Msb0, u8>, field_a: &str) -> Result<(), DekuError> {
        let value = field_a.parse::<u8>().unwrap();
        value.write(output, ())
    }
}

fn main() {
    let mut packet = Packet {
        header: Header { name_len: 7 },
        name: "Testing".to_string(),
    };
    assert_eq!(packet.header.name_len, 7);
    packet.name = "TestingTesting".to_string();
    packet.update().unwrap();
    assert_eq!(packet.header.name_len, 14);
}
```

For more complex headers, you might wanna implement `update()` for `Header` yourself, and just call that from `Packet` with the fields as the arguments much like the normal way of doing this.

**Comment by ciarant** [comment]
Thanks so much for taking the time to write up such a detailed reply. I'll untangle the mess I made of it and instead use the approach you've outlined :-)

**Comment by sharksforarms** [comment]
The ergonomics here are not ideal I must say. It may be useful to have a `post_update` attribute which is "arbitrary code"

Maybe something which looks like:
```rust
    #[deku(
        count = "...",
        map = "...",
        writer = "..."
        post_update = "self.header.name_len = self.name.len().try_into()?;"
    )]
    name: String,

```
