### ISSUE TITLE
bitvec 1.0.0 support

### ISSUE THREAD

**Issue by wcampbell0x2a** [sharksforarms/deku#243]
version v1.0.0-rc2 is currently out. We should try and support v1.0.0 before it's eventual release.

**Comment by sharksforarms** [comment]
Also saw this! Wanna give it a go? I may have time next week.

**Comment by wcampbell0x2a** [comment]
> Also saw this! Wanna give it a go? I may have time next week.

I almost did it but realized there were some breaking API changes such as the removal of `as_raw_slice()`, so didn't have time to move it to that version.

**Comment by wcampbell0x2a** [comment]
Closed with https://github.com/sharksforarms/deku/pull/281
