### ISSUE TITLE
Support no_std environments without alloc

### ISSUE THREAD

**Issue by jhbruhn** [sharksforarms/deku#248]
How fundamental is the use of alloc in this library? It would be nice to be able to use (a subset) of this crate on no_std targets which don't have a global allocator. The parsing and serialization alone should be possible without that if I understand this crate correctly.

**Comment by sharksforarms** [comment]
Pretty fundamental. I added the feature to make it extensible in the future. The BitVec type is used to serialize the final byte output, so probably not during writing. It might be possible to do some reading. I've never actually tried/had a use case for a platform without an allocator. I would recommend giving it a try and see'ing if it works for you.

**Comment by sharksforarms** [comment]
Closing for now

**Comment by ImUrX** [comment]
why was this closed?

**Comment by sharksforarms** [comment]
> why was this closed?

See my previous reply here: https://github.com/sharksforarms/deku/issues/248#issuecomment-1049863195

alloc is pretty fundamental to the crate as it stands. If you have any proposals, questions or input, please open an issue. Thanks!

**Comment by ImUrX** [comment]
yeah I understood the reason why ``alloc`` is used, I dont understand why this issue is closed though. 

If you don't plan to add this feature you can close it as not planned, or just leave it open if you are open to listening to ideas.

**Comment by sharksforarms** [comment]
> If you don't plan to add this feature you can close it as not planned, or just leave it open if you are open to listening to ideas.

See my previous reply.

>  If you have any proposals, questions or input, please open an issue.
