### ISSUE TITLE
Question: How to use a BufReader with Deku

### ISSUE THREAD

**Issue by ciarant** [sharksforarms/deku#252]
Hey there. I working on a tool to decode a proprietary legacy binary file format and am struggling to find an example of how I might be able to use a BufReader with Deku. What would allow me to not worry about buffering data myself while also avoiding loading the entire binary file into memory? Anyone got a pointers?

(I'm a newcomer to Rust so, apologies, this might be a dumb question)

Here's a [code snippet](https://github.com/ciarant/deku-example/blob/1bdd4351435d2729af277695bd7164bcab0e359b/src/lib.rs#L41) (it's waaaay simpler than the format I have to deal with, but might help ¯\_(ツ)_/¯)

**Comment by wcampbell0x2a** [comment]
@sharksforarms would this require something like https://github.com/sharksforarms/deku/issues/105?

I'd also like a solution to this use case.

**Comment by wcampbell0x2a** [comment]
With https://github.com/sharksforarms/deku/pull/352 this "Just Works". Closing unless you have other questions for this.
