### ISSUE TITLE
`const_generics` feature doesn't work without `std` feature

### ISSUE THREAD

**Issue by dullbananas** [sharksforarms/deku#262]
Enabling `const_generics` but not `std` causes an error here:

https://github.com/sharksforarms/deku/blob/31ffd8db236e5153f57c66fac7db85acb277947a/src/impls/slice.rs#L170

**Comment by sharksforarms** [comment]
we can `use core::mem::MaybeUninit` here, fixed in https://github.com/sharksforarms/deku/commit/10d05a6c70a835996d8a4ac5d4b832355c9a924b
