### ISSUE TITLE
Implement `DekuWrite` for `[T]`

### ISSUE THREAD

**Issue by constfold** [sharksforarms/deku#270]
Currently we alreay have `DekuWrite` for `&[T]`, I think there is no reason to not have `DekuWrite` on `[T]`. I found this would be convenience while write codes like:
```
self.0.as_ref().write(output, ()) // not work, type annotations needed
<&[u8]>::write(self.0.as_ref(), output, ()) // not work either
<&[u8]>::write(&self.0.as_ref(), output, ()) // works
<[u8]>::write(self.0.as_ref(), output, ()) // works
```

**Comment by wcampbell0x2a** [comment]
Should be closed with https://github.com/sharksforarms/deku/pull/416
