### ISSUE TITLE
`Option<Vec<...>>` fields that use `cond` and `until` don't work as expected (?)

### ISSUE THREAD

**Issue by vext01** [sharksforarms/deku#286]
Hi,

Just found `deku` recently. Fantastic work, many thanks.

Should `<Option<Vec<...>>` fields work with `cond` and `until` attributes?

Example:
```
use deku::prelude::*;

#[derive(Debug, PartialEq, DekuRead, DekuWrite)]
struct DekuTest {
    has_data: u8,
    #[deku(cond = "*has_data != 0", until = "|e: &Thing| e.0 == 0xff")]
    data: Option<Vec<Thing>>,
}

#[derive(Debug, PartialEq, DekuRead, DekuWrite)]
struct Thing(u8);

fn main() {
    let data: Vec<u8> = vec![0x01, 0xBE, 0xEF, 0xFF, 0xFF];
    let (_rest, val) = DekuTest::from_bytes((data.as_ref(), 0)).unwrap();

    assert_eq!(DekuTest {
        has_data: 1,
        data: Some(vec![Thing(0xBE), Thing(0xEF), Thing(0xff)]),
    }, val);
}
```

Gives:
```
error[E0277]: the trait bound `Thing: std::marker::Copy` is not satisfied
 --> src/main.rs:3:28
  |
3 | #[derive(Debug, PartialEq, DekuRead, DekuWrite)]
  |                            ^^^^^^^^ the trait `std::marker::Copy` is not implemented for `Thing`
  |
  = help: the trait `deku::DekuRead<'a, Ctx>` is implemented for `Option<T>`
  = note: required because of the requirements on the impl of `std::marker::Copy` for `Limit<Thing, [closure@src/main.rs:6:45: 6:70]>`
  = note: required because it appears within the type `(Limit<Thing, [closure@src/main.rs:6:45: 6:70]>, ())`
  = note: required because of the requirements on the impl of `deku::DekuRead<'_, (Limit<Thing, [closure@src/main.rs:6:45: 6:70]>, ())>` for `Option<Vec<Thing>>`
  = note: this error originates in the derive macro `DekuRead` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `Thing` with `#[derive(Copy)]`
  |
11| #[derive(Copy)]
  |
```

Adding `Clone` and `Copy` to `Thing` makes it work, but maybe I don't want `Thing` to be `Copy`...

What's odd is that if you have either:
 - Just a `Vec<Thing>` and a `until` attribute, or
 - Just an `Option<Thing>` and a `cond` attribute...

Then `Copy` is not required. It has do be when these features are composed.

Any ideas? Or user error?

**Comment by sharksforarms** [comment]
Hi @vext01, on my phone atm will be at a computer tomorrow.

My initial thought is that the `until` is getting applied to the `Option<T>` which may be related to https://github.com/sharksforarms/deku/issues/125

What you can do to get around this is making a wrapper struct with a Vec containing the until, then use that struct in your Option. If you need an example i can provide one tomorrow.

**Comment by vext01** [comment]
> What you can do to get around this is making a wrapper struct with a Vec containing the until, then use that struct in your Option. If you need an example i can provide one tomorrow.

Yeah, I realised this shortly after posting.

Perhaps you should disallow both `cond` and `until` to be applied together on any given field?

**Comment by sharksforarms** [comment]
`cond` can be used in combination with `until`, one could imagine the following scenario:

```
use deku::prelude::*;
use std::convert::{TryFrom, TryInto};

#[derive(Debug, PartialEq, DekuRead, DekuWrite)]
struct DekuTest {
    should_read_data: u8,
    #[deku(cond = "*should_read_data == 1", until = "|v: &u8| *v == 0")]
    field: Vec<u8>,
}

fn main() {
    // should_read_data = 1
    let data: Vec<u8> = vec![1, b'H', b'e', b'l', b'l', b'o', 0];
    let value = DekuTest::try_from(data.as_ref()).unwrap();
    
    assert_eq!(
        DekuTest {
            should_read_data: 1,
            field: b"Hello\0".to_vec(),
        },
        value
    );


    // should_read_data = 0
    let data: Vec<u8> = vec![0, b'H', b'e', b'l', b'l', b'o', 0];
    let (rest, value) = DekuTest::from_bytes((data.as_ref(), 0)).unwrap();
    
    assert_eq!(
        DekuTest {
            should_read_data: 0,
            field: vec![],
        },
        value
    );
    assert_eq!(rest.0, vec![b'H', b'e', b'l', b'l', b'o', 0]);
}
```

[link](https://www.rustexplorer.com/b#%2F*%0A%5Bdependencies%5D%0Adeku%20%3D%20%22*%22%0A*%2F%0A%0Ause%20deku%3A%3Aprelude%3A%3A*%3B%0Ause%20std%3A%3Aconvert%3A%3A%7BTryFrom%2C%20TryInto%7D%3B%0A%0A%23%5Bderive(Debug%2C%20PartialEq%2C%20DekuRead%2C%20DekuWrite)%5D%0Astruct%20DekuTest%20%7B%0A%20%20%20%20should_read_data%3A%20u8%2C%0A%20%20%20%20%23%5Bdeku(cond%20%3D%20%22*should_read_data%20%3D%3D%201%22%2C%20until%20%3D%20%22%7Cv%3A%20%26u8%7C%20*v%20%3D%3D%200%22)%5D%0A%20%20%20%20field%3A%20Vec%3Cu8%3E%2C%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20%2F%2F%20should_read_data%20%3D%201%0A%20%20%20%20let%20data%3A%20Vec%3Cu8%3E%20%3D%20vec!%5B1%2C%20b'H'%2C%20b'e'%2C%20b'l'%2C%20b'l'%2C%20b'o'%2C%200%5D%3B%0A%20%20%20%20let%20value%20%3D%20DekuTest%3A%3Atry_from(data.as_ref()).unwrap()%3B%0A%20%20%20%20%0A%20%20%20%20assert_eq!(%0A%20%20%20%20%20%20%20%20DekuTest%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20should_read_data%3A%201%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20field%3A%20b%22Hello%5C0%22.to_vec()%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20value%0A%20%20%20%20)%3B%0A%0A%0A%20%20%20%20%2F%2F%20should_read_data%20%3D%200%0A%20%20%20%20let%20data%3A%20Vec%3Cu8%3E%20%3D%20vec!%5B0%2C%20b'H'%2C%20b'e'%2C%20b'l'%2C%20b'l'%2C%20b'o'%2C%200%5D%3B%0A%20%20%20%20let%20(rest%2C%20value)%20%3D%20DekuTest%3A%3Afrom_bytes((data.as_ref()%2C%200)).unwrap()%3B%0A%20%20%20%20%0A%20%20%20%20assert_eq!(%0A%20%20%20%20%20%20%20%20DekuTest%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20should_read_data%3A%200%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20field%3A%20vec!%5B%5D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20value%0A%20%20%20%20)%3B%0A%20%20%20%20assert_eq!(rest.0%2C%20vec!%5Bb'H'%2C%20b'e'%2C%20b'l'%2C%20b'l'%2C%20b'o'%2C%200%5D)%3B%0A%7D)

Closing for now, feel free to re-open if needed!
