### ISSUE TITLE
Is deku fast?

### ISSUE THREAD

**Issue by vext01** [sharksforarms/deku#288]
Hi,

Do we have any idea if deku generates fast parsers?

Cheers

**Comment by wcampbell0x2a** [comment]
I have done some work recently to improve the speed of the deku generated parsers. 

We don't have benchmarks against just writing a parser by hand. My only note is that if you are only using this to parse bytes then your performance will suffer quite a bit, as our backend [bitvec](https://github.com/bitvecto-rs/bitvec) works on bit slices.

See #25

**Comment by sharksforarms** [comment]
There are some trade-offs, yes. Not to say these couldn't be solved given some effort / time. I would recommend doing comparisons/benchmarks yourself and see if it meets your requirements.
