### ISSUE TITLE
Using Deku alongside BitVec prelude causes multiple applicable items in scope error

### ISSUE THREAD

**Issue by Nikola-Milovic** [sharksforarms/deku#289]
Hello, I am now to Rust but I am pretty sure that this isn't a very big deal but it might be useful to have a note of this.

Basically if you try and use `BitVec` and `Deku` alongside each other

```
use bitvec::prelude::*;
use deku::prelude::*;
```

You will encounter the following error

```
error[E0034]: multiple applicable items in scope
 --> src/main.rs:4:28
  |
4 | #[derive(Debug, PartialEq, DekuRead, DekuWrite)]
  |                            ^^^^^^^^ multiple `view_bits` found
  |
  = note: candidate #1 is defined in an impl of the trait `deku::bitvec::BitView` for the type `[T]`
  = note: candidate #2 is defined in an impl of the trait `bitvec::view::BitView` for the type `[T]`
  = note: this error originates in the derive macro `DekuRead` (in Nightly builds, run with -Z macro-backtrace for more info)
help: disambiguate the associated function for candidate #1
  |
4 | #[derive(Debug, PartialEq, deku::bitvec::BitView::view_bits(&DekuRead), DekuWrite)]
  |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
help: disambiguate the associated function for candidate #2
  |
4 | #[derive(Debug, PartialEq, bitvec::view::BitView::view_bits(&DekuRead), DekuWrite)]
  |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

You can fix this by removing the prelude import of `BitVec` which will remove the `bitvec::BitView` from the scope.

The full code to replicate the issue

`Cargo.toml`
```toml
[package]
name = "deku-issue"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1"
deku = "0.14"
```

`main.rs`
```rust
use bitvec::prelude::*;
use deku::prelude::*;

#[derive(Debug, PartialEq, DekuRead, DekuWrite)]
#[deku(endian = "big")]
//Fields are not important I just copied the example from the docs
struct DekuTest {
    #[deku(bits = "4")]
    field_a: u8,
    #[deku(bits = "4")]
    field_b: u8,
    field_c: u16,
}

fn main() {
    println!("Hello, world!");
}
``` 

If we follow the error message and try and use the suggestion
```rust
#[derive(Debug, PartialEq, bitvec::view::BitView::view_bits(&DekuRead), DekuWrite)]
```

We get the following error
```
rustc: expected unsuffixed literal or identifier, found `&`
```

**Comment by wcampbell0x2a** [comment]
I'm not at my computer, but we don't use `bitvec = 1` and instead use `bitvec = "0.22.1"`. If the versions match you should be good.

**Comment by sharksforarms** [comment]
Deku also re-exposes bitvec under deku::bitvec https://docs.rs/deku/latest/deku/bitvec/index.html

I'm not a fan of this either, if I were to refactor the crate I wouldn't re-expose bitvec but rather keep it an implementation detail.

**Comment by wcampbell0x2a** [comment]
> Deku also re-exposes bitvec under deku::bitvec https://docs.rs/deku/latest/deku/bitvec/index.html
> 
> I'm not a fan of this either, if I were to refactor the crate I wouldn't re-expose bitvec but rather keep it an implementation detail.

I like the re-expose, thus I don't need to worry about the version. Unless there is a better pattern for this.

**Comment by sharksforarms** [comment]
> I like the re-expose, thus I don't need to worry about the version

There's pros & cons. Cons being now you're fixed to using the version of bitvec defined by deku (which atm doesn't follow bitvec's versioning / updates)

I generally don't like this pattern from the perspective of a library as it's confusing to clients as described in OP (especially if it's in a prelude scenario, now you'd need to alias the bitvec library you want to use to say `bitvec_other` or something).

Instead of exposing bitvec's types, deku could thinly-wrap these types and keep the implementation details hidden

**Comment by Nikola-Milovic** [comment]
I'll pinch in coming from ecosystems other than Rust, I'd as well prefer keeping `BitVec` out of `Deku`s public API, feels wrong that I have to use a library from within another library. Either wrap it and expose `Deku` wrapped alternatives or use it internally. Again its not that big of a deal, its easy to just `use` the `Deku` version but it doesn't feel natural

**Comment by sharksforarms** [comment]
Noted in https://github.com/sharksforarms/deku/issues/290 will close the issue for now
