### ISSUE TITLE
Can't build due to outdated bitvec

### ISSUE THREAD

**Issue by lmpynix** [sharksforarms/deku#296]
Latest version of Deku depends on `bitvec = "0.22.1"` which itself depends on `funty = "1.2"`.  This version of `funty` was yanked after bitvecto-rs/funty#3 and Deku no longer builds.  Later versions of `bitvec` depend on the later (not yanked) versions instead.

It seems like #281 already exists to fix this, but as of a few hours ago that PR is probably necessary to build Deku again.

**Comment by vext01** [comment]
I was using `BitSlice::as_raw_slice()`, which they've removed.

I was converting the remaining bytes returned by a deku `read()` back into a `&[u8]`. Seems this is no longer possible.

The bitvec docs says to use `BitSlice::domain()`, but I don't see how that helps.

**Comment by vext01** [comment]
Well I fixed it by just not going back to `&[u8]` and working on a `BitSlice` instead. It's kind of annoying, as it forces me to work at bit-level granularity, but at the time I was using `as_raw_slice()`, I knew the `BitSlice` was a multiple of 8-bits in length.

Oh well.

**Comment by sharksforarms** [comment]
Can you use `.domain().region().unwrap().1`? This is what deku uses, see: https://github.com/sharksforarms/deku/pull/281/files

**Comment by hanusek** [comment]
I have a [problem](https://github.com/sharksforarms/deku/issues/303) with deku 13.0.1. I need compatibility with rust 1.54.
Unfortunately, `deku 15.0` an `bitvec 1.0.0` have not.
https://lib.rs/compat/bitvec
https://lib.rs/compat/deku
