### ISSUE TITLE
`DekuWrite`: multiple `write` found

### ISSUE THREAD

**Issue by kraktus** [sharksforarms/deku#301]
Hello, first of all thank you for your work!

Wanting to benchmark `deku` against `binrw`, the following code fails to compile.
```rust
#[derive(DekuRead, DekuWrite, BinRead, BinWrite)]
struct TestCompression{
    pub a: u64,
    pub b: u64,
    pub c: u64,
}
```

```
76  | #[derive(DekuRead, DekuWrite, BinRead, BinWrite)]
    |                    ^^^^^^^^^ multiple `write` found
    |
    = note: candidate #1 is defined in an impl of the trait `BinWrite` for the type `u64`
note: candidate #2 is defined in the trait `DekuWrite`
   --> /Users/solal/.cargo/registry/src/github.com-1ecc6299db9ec823/deku-0.15.0/src/lib.rs:321:5
    |
321 | /     fn write(
322 | |         &self,
323 | |         output: &mut bitvec::BitVec<u8, bitvec::Msb0>,
324 | |         ctx: Ctx,
325 | |     ) -> Result<(), DekuError>;
    | |_______________________________^
    = note: this error originates in the derive macro `DekuWrite` (in Nightly builds, run with -Z macro-backtrace for more info)
help: disambiguate the associated function for candidate #1
    |
76  | #[derive(DekuRead, BinWrite::write(&DekuWrite, DekuWrite, DekuWrite), BinRead, BinWrite)]
    |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
help: disambiguate the associated function for candidate #2
    |
76  | #[derive(DekuRead, DekuWrite::write(&DekuWrite, DekuWrite, DekuWrite), BinRead, BinWrite)]
    |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

looking at the expanded code (code very similar for `DekuContainerWrite::to_bits`) :
```rust
impl DekuWrite<()> for TestCompression {
    #[allow(unused_variables)]
    fn write(
        &self,
        __deku_output: &mut ::deku::bitvec::BitVec<u8, ::deku::bitvec::Msb0>,
        _: (),
    ) -> Result<(), ::deku::DekuError> {
        match *self {
            TestCompression { ref a, ref b, ref c } => {
                a.write(__deku_output, ())?;
                b.write(__deku_output, ())?;
                c.write(__deku_output, ())?;
                Ok(())
            }
        }
    }
}
```

I think the issue is that the fully qualified syntax is not used, such as  `<a as ::deku::DekuWrite>::write(__deku_output, ())?` or `::deku::DekuWrite::write(a, __deku_output, ())?`

**Comment by sharksforarms** [comment]
That's correct, thanks for reporting. I would accept a PR fixing this bug.

**Comment by sharksforarms** [comment]
Fixed in df8775d8f1, are you able to give it a try using the master branch? Thanks!

**Comment by kraktus** [comment]
Thanks for the quick fix, master is working 👍

**Comment by sharksforarms** [comment]
Thanks for reporting

**Comment by v1gnesh** [comment]
@kraktus, very interested in your findings, especially for reads.

**Comment by kraktus** [comment]
@v1gnesh Hey, the bench code can be found here: https://github.com/kraktus/helpmate-tb/blob/89093481cde389880199b4595d8ff6bdd1265886/lib/benches/serialise.rs. I compared `binrw`, `deku`, handwritten serialisation and `bitcode` (which while not allowing to specify a specific format was a useful baseline).

Note that the structs I have to write do **not need any bit-level** fiddling, unlike most use of `deku`.

Write results: 
- deku: 23ms
- binrw: 0.6ms
- handwritten (named custom in the bench): 0.5ms
- bincode: 0.7ms

Read results: 
- deku: 2.7ms
- binrw: 3.5ms
- handwritten (named custom in the bench): 0.07ms
- bincode: 0.7ms

Handwritten code is the winner for simple structs. I think the perf of `deku` could largely be improved by skipping completely using `bitvec` when the struct does not need it, and work directly with `Vec<u8>` but that would require almost duplicating the codebase.

**Comment by wcampbell0x2a** [comment]
This looks about right, with a couple of surprises, thanks for doing it.

I'm kinda surprised that `binrw` took the same as `deku` for reading. I thought it was emitting simple code for this, I'll have to take a look at that. Maybe they do less at compile time then I thought. I'll have to focus a bit more on deku writing when I come back to perf problems.

> Handwritten code is the winner for simple structs. I think the perf of deku could largely be improved by skipping completely using bitvec when the struct does not need it, and work directly with Vec<u8> but that would require almost duplicating the codebase.

Yah, this would be excellent. I might try and prototype this someday when I have the time.
