### ISSUE TITLE
Deku v0.13.0/v0.12.6 - cannot download 

### ISSUE THREAD

**Issue by hanusek** [sharksforarms/deku#303]
Hello.
I have problem with download `deku v0.13.0` 
https://lib.rs/compat/deku

I have rustc 1.54 ([yocto](https://layers.openembedded.org/layerindex/branch/honister/recipes/?q=rust)). I need deku version compatibility with 1.54.    
How to fix it?

log `0.12.6`:
```
error: failed to select a version for the requirement `deku = "=0.13.0"`
candidate versions found which didn't match: 0.15.1, 0.15.0, 0.14.1, ...
location searched: crates.io index
```

log `0.13.0`:
```
error: failed to select a version for the requirement `funty = "~1.2"`
candidate versions found which didn't match: 2.0.0, 1.1.0, 1.0.1, ...
location searched: crates.io index
required by package `bitvec v0.22.1`
    ... which satisfies dependency `bitvec = "^0.22.1"` of package `deku v0.12.6`
    ... which satisfies dependency `deku = "=0.12.6"` of package `auth v0.1.0 (/home/mhanusek/work/code/cybersec/auth/server)`
```

**Comment by sharksforarms** [comment]
Sorry I don't have a solution to this, nor do I have plans on supporting older versions of rustc apart from best effort. I am willing to accept pull requests which fix backwards compatability to versions of rustc.
