### ISSUE TITLE
Conditional DekuWrite

### ISSUE THREAD

**Issue by whati001** [sharksforarms/deku#403]
Hi all,

would it be possible to add support for conditional write?
For example, I would like to skip the serialization of specific fields based on there value as explained in the example below:

Struct to serialize into binary:

```rust
#[derive(Debug, Serialize, DekuWrite)]
pub struct StructEntry<T>
where
    T: DekuWrite,
{
    pub fieldA : u8,
    pub fieldB : T,
    #[deku(skip)]
    pub serialize: bool,
}

pub struct StructType {
    #[deku(cond = "self.serialize == true")]
    pub entryA: StructEntry<u32>,
    #[deku(cond = "self.serialize == true")]
    pub entryB: StructEntry<u32>,
```

And now, I would like to skip the serialization based on the `serialize` flag.
```rust
let mut config = StructType::Default; // assumed that Default is implemented
config.fieldA.serialize = false;
let bytes = StructType::to_bytes(&config).unwrap();
```

I have tried to use `#[serde(skip_serializing_if = ..`, but this has not worked for me.

**Comment by wcampbell0x2a** [comment]
Deku does not have a `skip_serializing_if` attribute, but could add this.

**Comment by whati001** [comment]
Hi @sharksforarms
Thank you very much for the quick feedback. You are right, seems like I have overseen to add the `skip` attribute.
Using the following deku `#[deku(skip, cond = '...']` works now for me.
