### ISSUE TITLE
Assert for tuple enum

### ISSUE THREAD

**Issue by libklein** [sharksforarms/deku#412]
I am wondering whether it is possible to define assertions over (anonymous) tuple structs, as in the following example:

```rust
#[derive(DekuRead, DekuWrite)]
#[deku(type = "u8", bits = "1")]
pub enum RegisterOrValue {
    #[deku(id = "0b0")]
    Field(#[deku(assert = "*??? < 32")] u8),
}
```

Is there some deku internal name that could be used to reference the parsed u8?

**Comment by sharksforarms** [comment]
Try the following: `#[deku(assert = "*field_0 < 32")] u8`

**Comment by wcampbell0x2a** [comment]
Closing, unless this didn't work for you!
