### ISSUE TITLE
Roll a release?

### ISSUE THREAD

**Issue by vext01** [sharksforarms/deku#428]
Hi,

Just wondering is there is any plan to roll a release any time soon?

I'm finding the new-style logging to be invaluable, but I have to use a git version to get it.

Cheers

**Comment by sharksforarms** [comment]
sounds like a good idea, @wcampbell0x2a which PRs would you like included in the next release? Is https://github.com/sharksforarms/deku/milestone/1 acurate?

**Comment by wcampbell0x2a** [comment]
Updated. Should be accurate.

**Comment by sharksforarms** [comment]
@wcampbell0x2a took a look, ping me on the PRs you'd like for me to look at and merge what you feel is ready. Thanks for your efforts!

**Comment by TaeHagen** [comment]
I also need https://github.com/sharksforarms/deku/pull/352 . Given it was merged many months ago, I assumed it would be included in a release, but was surprised to find out otherwise. A release would be appreciated!

**Comment by sharksforarms** [comment]
Getting there, @wcampbell0x2a has been doing some awesome work. Finding the time to review. Thanks for your patience 🙏

**Comment by sharksforarms** [comment]
@wcampbell0x2a I think we're good to cut a release from current master, wdyt? anything else you'd like to get in?

**Comment by wcampbell0x2a** [comment]
Yep! Should be good to go for the base release.

**Comment by sharksforarms** [comment]
0.17 is now released :tada: 

https://crates.io/crates/deku/0.17.0

**Comment by wcampbell0x2a** [comment]
Whoops, I don't think you updated the Cargo.toml version, as well as create tags :)

**Comment by sharksforarms** [comment]
yep forgot to push the tags, the cargo toml should be good?

**Comment by wcampbell0x2a** [comment]
You mind if I create a GitHub release with the CHANGELOG in it?

**Comment by sharksforarms** [comment]
> You mind if I create a GitHub release with the CHANGELOG in it?

Go for it! It's a good idea to start doing this
