### ISSUE TITLE
Differing impls for bits and bytes

### ISSUE THREAD

**Issue by sharksforarms** [sharksforarms/deku#44]
If `bytes` attribute is used and the index is on a byte boundary, it may be quicker to read from a slice of &[u8] instead of reading 8*n bits.

I'd like for more benchmarks to be written before so this optimization can be measured

One option could be to feature flag the bits/bytes attributes

**Comment by constfold** [comment]
Since #61 has been merged, this could be done by:
1. Add a new type `ByteSize`
2. Add specialization like `impl DekuRead<ByteSize> for xxx`
3. bytes uses type `ByteSize`, bits uses type `BitSize`, then compiler will decide which impl should be called.

**Comment by sharksforarms** [comment]
Great idea, I'd like to see a better suite of benchmarks before this is tackled so we can measure the difference

https://github.com/sharksforarms/deku/issues/25

**Comment by wcampbell0x2a** [comment]
Closing, the reader does this
