### ISSUE TITLE
Comply to `cond` attribute while encoding

### ISSUE THREAD

**Issue by fbergero** [sharksforarms/deku#448]
Should `cond` attribute make it so `deku` does not encode conditional fields even if they are `Some(_)`?

Specifically, shouldn't `field_b` be excluded from encoding here:
```
TestStruct {
            field_a: 0x02,
            field_b: Some(0x02),
        },
```
from https://github.com/sharksforarms/deku/blob/master/tests/test_attributes/test_cond.rs#L33.

Perhaps we need a `cond_write` attribute?

**Comment by sharksforarms** [comment]
take a look at `skip`: https://docs.rs/deku/latest/deku/attributes/index.html#skip

**Comment by fbergero** [comment]
Yeah, what I'm trying to achieve is the following:
```rust
    #[derive(PartialEq, Debug, DekuRead, DekuWrite)]
    struct TestStruct {
        field_a: u8,
        #[deku(cond = "*field_a == 0x01", assert = "field_b.is_some() || *field_a != 0x01")]
        field_b: Option<u8>,
    }

    let ret_read = TestStruct {
            field_a: 0x01,
            field_b: None,
    };

    let ret_write: Vec<u8> = ret_read.try_into().unwrap();
    assert_eq!(vec![0x1], ret_write);
```

to ensure that if `field_a == 0x01` then, `field_b` *has to be present*.
This passes without the `assert`.

This one using `skip` also passes, which I think it shouldn't?
```rust
 #[derive(PartialEq, Debug, DekuRead, DekuWrite)]
    struct TestStruct {
        field_a: u8,
        #[deku(cond = "*field_a != 0x01", skip)]
        field_b: Option<u8>,
    }

    let ret_read = TestStruct {
            field_a: 0x01,
            field_b: None,
    };

    let ret_write: Vec<u8> = ret_read.try_into().unwrap();
    assert_eq!(vec![0x1], ret_write);
```

All that said, would the `assert` be the right way to express my intention here?

**Comment by sharksforarms** [comment]
@fbergero ah I see, you want to enforce when writing. Yes, `assert` would be how you'd interrupt the reading/writing of bytes if a condition is not met. Does this satisfy your requirements? Does the `skip` case make sense to you on why it still writes? Since it's an `Option` type, field_a == 0x01 and so the condition is false, so we write the option (which is None, so nothing to write)

**Comment by fbergero** [comment]
Yeah this satisfies my requirement. And also I do understand why the `skip` works as is.
What is odd is that in this case the `DekuRead` would fail to parse the encoded version with `skip`. 
```rust
use deku::prelude::*;
use std::convert::TryFrom;

#[derive(PartialEq, Debug, DekuRead, DekuWrite)]
struct TestStructSkip {
    field_a: u8,
    #[deku(cond = "*field_a != 0x01", skip)]
    field_b: Option<u8>,
}

fn main() {

    {
        let test_data = TestStructSkip {
                field_a: 0x01, // field_a is not 0x01
                field_b: None, // so field_b is not Some
        };

        let ret_write: Vec<u8> = test_data.try_into().unwrap();
        TestStructSkip::try_from(&ret_write[..]).unwrap();
    }
}
```

In my case encoding that Struct without a `field_b=None` would make the binary representation invalid.

I'll close this anyhow. Thanks for your help.
