### ISSUE TITLE
Support unit structure `struct S;` in derive-macro `DekuWrite`

### ISSUE THREAD

**Issue by yuan-y-chang** [sharksforarms/deku#449]
We should support unit structure `struct S;` since `struct S {}` and `struct S();` are allowed to derive `DekuWrite`.
```rust
#[derive(DekuWrite)] // error: expected tuple struct or tuple variant, found unit struct `Zero`
#[deku(magic = b"\x00")]
struct Zero;
```
And `DekuRead` is no error here.

**Comment by wcampbell0x2a** [comment]
https://github.com/sharksforarms/deku/pull/450 should fix this.
