### ISSUE TITLE
Conditional Skip

### ISSUE THREAD

**Issue by wcampbell0x2a** [sharksforarms/deku#63]
Great idea of a library.

I have a protocol that needs conditional parsing of fields in a struct. I see the skip attribute, but would something like a conditional skip be possible?

```
use deku::prelude::*;
use std::convert::TryFrom;

#[derive(PartialEq, Debug, DekuRead, DekuWrite)]
pub struct DekuTest {
    pub field_a: u8,
    #[deku(skip, if=(field_a, 1))]
    pub field_b: Option<u8>,
    #[deku(skip, if=(field_b, Some(1)))]
    pub field_c: Option<u8>,
}

fn main() {
    let data: Vec<u8> = vec![0x01, 0x02];

    let value = DekuTest::from_bytes((data.as_ref(), 0)).unwrap();
    println!("{:#?}", value)
}
```

**Comment by sharksforarms** [comment]
I like the idea! Shouldn't be too hard to implement. I can get to it next week most likely

**Comment by sharksforarms** [comment]
For now, there is a `cond` attribute which you may find useful

**Comment by sharksforarms** [comment]
If you don't mind taking a look to see if it meets your use-case, I plan on making a release tomorrow morning

**Comment by wcampbell0x2a** [comment]
I shall

**Comment by wcampbell0x2a** [comment]
Perfect, works as expected
