### ISSUE TITLE
Why `from_bytes` need `bit_offset`

### ISSUE THREAD

**Issue by constfold** [sharksforarms/deku#68]
https://github.com/sharksforarms/deku/blob/c7e0377001794a1addd3b78ae8b60625afee3d11/src/lib.rs#L235
Why not `from_bytes(bytes: Bytes)` and `from_bits(bits: Bits)`? Why do I need to care about which bit the byte start from when I use a function called `from_bytes`?

**Comment by sharksforarms** [comment]
This is to make it so the function can consume the 'rest' easily. Since we're dealing with bits, not everything is byte alligned

Consider the following example:

```rust
use deku::prelude::*;

#[derive(Debug, PartialEq, DekuRead, DekuWrite)]
struct Struct1 {
    #[deku(bits = "5")]
    field_a: u8,
}

#[derive(Debug, PartialEq, DekuRead, DekuWrite)]
struct Struct2 {
    #[deku(bits = "3")]
    field_a: u8,
    field_b: u8,
}

fn main() {
    let test_data: &[u8] = [
        0b10101_010,
        0xAB,
    ]
    .as_ref();

    let (rest, s1) = Struct1::from_bytes((test_data, 0)).unwrap(); // bit_offset = 0

    assert_eq!(
        rest,
        ([0b10101_010, 0xAB].as_ref(), 5) // bit_offset = 5
    );

    assert_eq!(
        Struct1 {
            field_a: 0b000_10101 // first 5 bits
        },
        s1
    );

    let (rest, s2) = Struct2::from_bytes(rest).unwrap(); // consume using rest, from bit_offset = 5

    assert_eq!(
        rest,
        ([].as_ref(), 0) // no more rest
    );

    assert_eq!(
        Struct2 {
            field_a: 0b00000_010, // last 3 bits
            field_b: 0xAB
        },
        s2
    );
}
```

**Comment by constfold** [comment]
Ah it makes sense. But one more questions: 
1. Why not `from_bits` if the function it's about reading in bits?
2. And why it returns the rest? We already have `DekuRead::read`(it don't require `input_is_le` etc. now).
IMHO if a type is a container, it should be the highest level type(no parent type). This means when I use `from_bytes` what I want is `let my_prototype = MyPrototype::from_bytes(my_data)`, no rest. If not so, why don't I use `Abc::read(my_data)`?

**Comment by sharksforarms** [comment]
> Ah it makes sense. But one more questions:
> 
> 1. Why not `from_bits` if the function is about reading in bits?
> 2. And why it returns the rest? We already have `DekuRead::read`(it don't require `input_is_le` etc. now).
>    IMHO if a type is a container, it should be the highest level type(no parent type). This means when I use `from_bytes` what I want is `let my_prototype = MyPrototype::from_bytes(my_data)`, no rest. If not so, why don't I use `Abc::read(my_data)`?

1. This is an API detail, most users will have access to a &[u8], this is easier to work with. The use of `BitVec` is sorta-ish a implementation detail.

2. We return the rest as a "streaming" model, `from_bytes` can be called over and over until it fails or needs more data. `try_from` can be used for a "complete" where all input must be consumed. It was inspired from this: https://docs.rs/nom/6.0.0-alpha1/nom/index.html#streaming--complete

**Comment by constfold** [comment]
Oh, I see. How do I decide which function(`from_bytes` or `read`) I should call? Is there some rules?

**Comment by sharksforarms** [comment]
Yes this may require some more thinking/documentation in terms of the API:

Container:
`from_bytes` is to be used when consuming from &[u8], returning the rest
`try_from` is to be used when consuming from &[u8] and you want it to fail if not all input is used

Field:
`read` / `write` are for field reading and writing, these are mostly helpers for the above, but are public so they can be used in reader/writer attributes

**Comment by constfold** [comment]
Should we use `#[doc(hidden)]` as we don't want user to use `read`/`write`?

**Comment by sharksforarms** [comment]
> Should we use `#[doc(hidden)]` as we don't want user to use `read`/`write`?

That's one option, however, would make it harder to write custom reader/writer functions like this: [(example/custom_reader_writer.rs)](https://github.com/sharksforarms/deku/blob/master/examples/custom_reader_and_writer.rs#L20)

**Comment by sharksforarms** [comment]
One option could be to doc(hidden) and document it inside of reader/writer attributes as an "Advanced" section

**Comment by constfold** [comment]
No, please don't. If it would be used, then don't hide it. And I will close this issue since I have got everything I want to know. (Though I still don't like it :P)
