### ISSUE TITLE
Rename `to_bitvec` to `to_bits`

### ISSUE THREAD

**Issue by constfold** [sharksforarms/deku#69]
Why a function convert a type to bytes (`Vec<u8>`) is `to_bytes` but a function convert type to bits(`BitVec<Msb0, u8>`) is `to_bitvec`? why not `to_bits`?
https://github.com/sharksforarms/deku/blob/c7e0377001794a1addd3b78ae8b60625afee3d11/src/lib.rs#L251-L255

**Comment by sharksforarms** [comment]
Fair enough :)
