### ISSUE TITLE
Implement DekuRead, DekuWrite for String

### ISSUE THREAD

**Issue by wcampbell0x2a** [sharksforarms/deku#82]
Maybe something like this? 
```
use deku::prelude::*;

#[derive(Debug, PartialEq, DekuRead, DekuWrite)]
struct Packet {
    s: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test01() {
        //                      [len  | string               ]
        let data: Vec<u8> = vec![5, 104, 101, 108, 108, 111];

        let (_, value) = Packet::from_bytes((data.as_ref(), 0)).unwrap();

        assert_eq!(
            Packet {
                s: "hello".to_string(),
            },
            value
        );
    }
}
```

(len would be an u64 in a real example)

**Comment by sharksforarms** [comment]
I've held off on implementing anything for String in favor of using a custom reader/writer or map, as this is more specific to the implementation of the protocol being serialized/deserialized. I.e. len (u8?, u16?, u64?) + value, null terminated, etc.

**Comment by knolljo** [comment]
Some examples in the documentation on how to parse common strings would be really helpful! 
For example for fixed size strings with \0 padding, cstrings, etc.

**Comment by wcampbell0x2a** [comment]
This is a pretty common use of CString and isn't documented in `deku`, probably should add that.

Anyway, this should work for you:
```rs
#[derive(Debug, DekuRead, DekuWrite)]
struct RawRecord {
    #[deku(pad_bytes_after = "4 - firstname.to_bytes_with_nul().len()")]
    firstname: CString,

    #[deku(pad_bytes_after = "5 - lastname.to_bytes_with_nul().len()")]
    lastname: CString,
}

```

**Comment by knolljo** [comment]
Thanks a lot! Very much appreciated!

**Comment by knolljo** [comment]
If I use this solution and Provide a string which is longer than or equal to the given pad bytes an "attempt to subtract with overflow" panikc occurs on trying to convert the Struct with `to_bytes`.
In Release Mode this doesn't happen, but the bytes are just truncated.
Shouldn't this give a DekuError?
I guess there needs to be a check that pad_bytes_after cannot be zero.
