### ISSUE TITLE
Test against upcoming `bitvec` release

### ISSUE THREAD

**Issue by sharksforarms** [sharksforarms/deku#85]
Test against bitvec `develop` branch:

https://twitter.com/bitvec_rs/status/1290692818353127426

**Comment by wcampbell0x2a** [comment]
Was going to leave a comment about the new bitvec release, but it looks like you already fixed a problem with it. 👍

**Comment by sharksforarms** [comment]
Thanks @wcampbell0x2a will be doing an update tomorrow if everything works out.
