### ISSUE TITLE
Reading Prior Field Values

### ISSUE THREAD

**Issue by inspier** [sharksforarms/deku#96]
Is there a way to read prior fields for example below for `field_02` to store a value that is the result of a function run on `field_01`.

```rust
pub struct SomeStruct {
field_01: u8,
field_02: u8,
}
```

**Comment by sharksforarms** [comment]
> Is there a way to read prior fields for example below for `field_02` to store a value that is the result of a function run on `field_01`.
> 
> ```rust
> pub struct SomeStruct {
> field_01: u8,
> field_02: u8,
> }
> ```

Hi! Yes. Check out the `map` and `reader` attributes. And possibly `default`. That should help you out.

https://docs.rs/deku/0.7.2/deku/attributes/index.html

I am away right now but can provide examples in a couple days.

**Comment by inspier** [comment]
Ah I completely misunderstood the semantics of skip, thanks appreciate the quick response.

**Comment by sharksforarms** [comment]
No problem. If you run into any blockers feel free to reach out!
